### ISSUE TITLE
No History.md

### ISSUE THREAD

**Issue by ghost** [afloury/Smart-Scavenger-Hunt#1]
Please log your daily activity in `HISTORY.MD`.  
The current file is a copy of `README.md`.

**Comment by Nicnl** [comment]
I'm not sure I understood what the issue is.

Currently, the two `HISTORY.MD` and `README.MD` files are different and both contains what they're supposed to.

______

### `README.MD`

<img width="664" alt="capture d ecran 2017-11-08 a 16 10 36" src="https://user-images.githubusercontent.com/1387951/32556435-b039b2a2-c49f-11e7-80fb-b561684becd8.png">

______

### `HISTORY.MD`

<img width="668" alt="capture d ecran 2017-11-08 a 16 10 25" src="https://user-images.githubusercontent.com/1387951/32556446-b4fe406e-c49f-11e7-8ea4-1044e98d3c32.png">

**Comment by ghost** [comment]
Weird. Either you hadn't pushed your commit yet when I checked, either I failed to click properly and thought HISTORY.md was a copy of README.md.

Either way: problem solved.
