### ISSUE TITLE
No tags

### ISSUE THREAD

**Issue by ghost** [afloury/Smart-Scavenger-Hunt#2]
Please tag your project daily

**Comment by Nicnl** [comment]
### The missing tags were created.

We'll do our best to tag the next days as well.

**Comment by Nicnl** [comment]
### Additional informations concerning this issue.

Because we may continue to work at home, we want to be absolutely sure the tag of a given day corresponds to it's last commit.

To do so, we plan to tag the last commit of the day `n-1` on day `n`.   
For instance, today's tag for branch master (`master-2017-11-08`) will be created tomorrow morning. _(2017-11-08)_
